config/routes.rb
TrlDictionary::Application.routes.draw do
  resources :languages do
    resources :words
  end
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'

  root :to => "languages#index"

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  
  has_many :microposts, :dependent => :destroy
  
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
    
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                   :length   => { :maximum => 50 }
  
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }

  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
  
  before_save :encrypt_password
  
  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  private
    
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  before_filter :signed_in_user, :only => [:new, :create]
  
  layout 'sign', :only => [:new]
  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def new
    @user = User.new
    @title = "Sign Up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Lexi!"
      redirect_to root_path
    else
      @title = "Sign Up"
      flash[:error] = "Check valid email and/or password."
      @user.password = ""
      @user.password_confirmation = ""
      redirect_to signup_path
    end
  end
  
  def edit
    @title = "Edit user"
  end
  
  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def destroy
    user = User.find(params[:id])
    unless current_user?(user)
      user.destroy
      flash[:success] = "User destroyed."
    else
      flash[:error] = "Cannot delete yourself."
    end
    redirect_to users_path
  end
  
  private
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
    
    def signed_in_user
      if signed_in?
        flash[:info] = "You are already logged in..."
        redirect_to root_path
      end
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, :size => 30 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? %>
	| <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
	                              :title => "Delete #{user.name}" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <%= link_to "change", "http://gravatar.com/emails", :target => "_blank" %>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1><%= link_to "Lexi", root_path %></h1>

<div class="block" id="block-signup">
	<h2>Sign Up</h2>
	<div class="content signup">
		 <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
				
			<%= form_for(:user, :url => users_path, :html => { :class => "form login"}) do |f| %>
			<div class="group wat-cf">
				<div class="left">
	    		<%= f.label :name, :class => "label right" %>
				</div>
				<div class="right">
	    		<%= f.text_field :name, :class => "text_field" %>
				</div>
			</div>
			<div class="group wat-cf">
				<div class="left">
	    		<%= f.label :email, :class => "label right" %>
				</div>
				<div class="right">
	    		<%= f.text_field :email, :class => "text_field" %>
				</div>
			</div>
			<div class="group wat-cf">
				<div class="left">
	    		<%= f.label :password, :class => "label right" %>
				</div>
				<div class="right">
	    		<%= f.password_field :password, :class => "text_field" %>
				</div>
			</div>
			<div class="group wat-cf">
				<div class="left">
	    		<%= f.label :password_confirmation, :class => "label right" %>
				</div>
				<div class="right">
	    		<%= f.password_field :password_confirmation, :class => "text_field" %>
				</div>
			</div>
			
			<div class="group navform wat-cf">
				<div class="right">
					<button class="button" type="submit">
			 			<img src="images/web-app-theme/icons/tick.png" alt="Save"> Sign Up
			  	</button>
				</div>
			</div>
			
			
			<% end %>
	</div>
</div>


<p>Already a User? <%= link_to "Login now!", signin_path %></p>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
		<td class="main">
			<h1>
			  <%= @user.name %>
			</h1>
		</td>
	  <td class="sidebar round">
	    <strong>Name</strong> <%= @user.name %><br />
	    <strong>URL</strong>  <%= link_to user_path(@user), @user %>
	  </td>
  </tr>
</table>