config/routes.rb
TrlDictionary::Application.routes.draw do
  resources :languages do
    resources :words
  end
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'

  root :to => "languages#index"

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :language
  
  attr_accessible :text, :translation, :ipa, :example
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  
  before_filter :authenticate, :except => [:index, :show]
  before_filter :find_language
  
  # GET /words
  # GET /words.xml
  def index
    @words = @language.words

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @words }
    end
  end

  # GET /words/1
  # GET /words/1.xml
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @word }
    end
  end

  # GET /words/new
  # GET /words/new.xml
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.xml
  def create
    @word = @language.words.build(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to(language_words_url(@language), :notice => 'Word was successfully created.') }
        format.xml  { render :xml => @word, :status => :created, :location => @word }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @word.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.xml
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to(language_words_url(@language), :notice => 'Word was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @word.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.xml
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to(language_words_url(@language)) }
      format.xml  { head :ok }
    end
  end

  protected
    
    def find_language
      @language = Language.find(params[:language_id])
    end
   
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for([@language, @word]) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :translation %><br />
    <%= f.text_field :translation %>
  </div>
  <div class="field">
    <%= f.label :ipa %><br />
    <%= f.text_field :ipa %>
  </div>
  <div class="field">
    <%= f.label :example %><br />
    <%= f.text_field :example %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word for <%= @language.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', language_words_path(@language) %>

app/views/words/index.html.erb
<% if signed_in? %>
	<div class="actions-right">
		<%= link_to(new_language_word_path(@language), :class => "button") do %>
			<%= image_tag "add.png" %>
			New Word
		<% end %>
	</div>
<% end %>

<h1>Words for <%= @language.name %></h1>

<table class="table">
  <tr>
    <th>Text</th>
    <th>Translation</th>
    <th>Ipa</th>
    <th class="sent-example">Example Sentence</th>
    <th></th>
		<% if signed_in? %>
	    <th></th>
	    <th></th>
		<% end %>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= word.text %></td>
    <td><%= word.translation %></td>
    <td><%= word.ipa %></td>
    <td><%= word.example %></td>
		<% if signed_in? %>
    	<td><%= link_to 'Edit', edit_language_word_path(word.language, word) %></td>
	    <td><%= link_to 'Delete', [word.language, word], :confirm => 'Are you sure?', :method => :delete %></td>
		<% end %>
  </tr>
<% end %>
</table>

<%= link_to 'Back', root_path %>

app/views/words/new.html.erb
<h1>New word for <%= @language.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', language_words_path(@language) %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @word.text %>
</p>

<p>
  <b>Translation:</b>
  <%= @word.translation %>
</p>

<p>
  <b>Ipa:</b>
  <%= @word.ipa %>
</p>

<p>
  <b>Example:</b>
  <%= @word.example %>
</p>


<%= link_to 'Edit', edit_language_word_path(@language, @word) %> |
<%= link_to 'Back', language_words_path(@language) %>