config/routes.rb
TrlDictionary::Application.routes.draw do
  resources :languages do
    resources :words
  end
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'

  root :to => "languages#index"

end

app/views/layouts/_footer.html.erb
<div id="footer">
		<ul class="foot_nav">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li>Copyright &copy; <%= Time.now.year %> Lexi.</li>
    </ul>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <h1>
  	<a href="/">Lexi</a>
  	<span class="tagline">The Lexicon Documenter</span>
	</h1>
  <div id="user-navigation">
    <ul class="wat-cf">
			<li><%= link_to "Home", root_path %></li>
			<% if signed_in? %>
			<li><%= link_to "Logout", signout_path, :method => :delete %></li>
			<% else %>
			<li><%= link_to "Login", signin_path %></li>
			<% end %>
    </ul>
  </div>
  <div id="main-navigation">
    <ul class="wat-cf"></ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lexi</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container" class="wat-cf">
    <%= render 'layouts/header' %>
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
				<div class="block">
					<div class="content">
							<div class="inner">
        				<%= yield %>
					</div>
				</div>
				</div>
      </div>
    </div>
    <%= render 'layouts/footer' %>

  </div>
</body>
</html>

app/views/layouts/application_temp.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web App</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Web App</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
          <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li>
          <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Web App.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/layouts/sign.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lexi</title>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="box">
      <%= yield %>
    </div>
  </div>
</body>
</html>